- hosts: "{{ hosts_keyword }}"
  tasks:
    - name: required packages
      pacman:
        name: "{{ item }}"
        state: latest
      loop:
        - screen
        - vim
        - openssh
        - wget
        - git
        - htop
        - net-tools
        - nmap
        - nginx
        - certbot
        - cronie
        - syslog-ng
        - docker
        - prometheus-node-exporter
        - base-devel
        - netctl
        - openvpn
        - iptables
        - sshguard
    - name: all but mail packages
      pacman:
        name: "{{ item }}"
        state: latest
      loop:
        - exim
      when: "'mail' not in group_names"
    - name: mail packages
      pacman:
        name: "{{ item }}"
        state: latest
      loop:
        - dovecot
        - mailman
      when: "'mail' in group_names"
    - name: ldap packages
      pacman:
        name: "{{ item }}"
        state: latest
      loop:
        - slapd
      when: "'ldap' in group_names"
