- hosts: "{{ hosts_keyword }}"
  tasks:
    - name: required packages for certificates
      pacman:
        name:
          - certbot
          - nginx
        state: latest
    - name: stop nginx
      systemd:
        state: stopped
        name: nginx
    - name: create certificate
      command: "certbot certonly --standalone -d {{ inventory_hostname }} {% for san in sans %} -d {{ san }} {% endfor %}"
      creates: /etc/letsencrypt
    - name: renew certificate
      command: "certbot renew --authenticator standalone --agree-tos"
    - name: ensure ssl group
      group:
        name: ssl
        state: present
        gid: 900
    - name: chgrp ssl
      file:
        path: /etc/letsencrypt
        group: ssl
        recurse: yes
    - name: chgrp ssl
      file:
        path: /etc/letsencrypt
        group: ssl
        recurse: yes
    - name: chmod 
      file:
        path: /etc/letsencrypt/
        mode: o-rwx
    - name: chmod 
      file:
        path: /etc/letsencrypt/live
        mode: g+x
    - name: chmod 
      file:
        path: /etc/letsencrypt/archive
        mode: g+x
    - name: restart nginx
      systemd:
        state: restarted
        name: nginx
