- hosts: all
  tasks:
    - name: required packages for certificates
      pacman:
        name:
          - certbot
          - certbot-dns-cloudflare
        state: latest
    - name: ensure cloudflare api key
      copy:
        content: "{{ certbot_dns_ini }}"
        dest: "{{ certbot_dns_ini_location }}"
        mode: '0600'
    - name: create certificate
      command:
        cmd: "certbot certonly --standalone -m postmaster@{{ domain }} --agree-tos -n -d {{ inventory_hostname }} {% for san in sans %} -d {{ san }} {% endfor %} --dns-cloudflare-credentials {{ certbot_dns_ini_location }}"
        creates: /etc/letsencrypt
    - name: renew certificate
      command: "certbot renew --preferred-challenges dns --agree-tos --dns-cloudflare-credentials {{ certbot_dns_ini_location }}"
    - name: cleanup ini
      file:
        path: "{{ certbot_dns_ini_location }}"
        state: absent
    - name: ensure ssl group
      group:
        name: ssl
        state: present
        gid: 900
    - name: chgrp ssl
      file:
        path: /etc/letsencrypt
        group: ssl
        recurse: yes
    - name: chgrp ssl
      file:
        path: /etc/letsencrypt
        group: ssl
        recurse: yes
    - name: chmod 
      file:
        path: /etc/letsencrypt/
        mode: o-rwx
        recurse: yes
    - name: chmod 
      file:
        path: /etc/letsencrypt/live
        mode: g+x
    - name: chmod 
      file:
        path: /etc/letsencrypt/archive
        mode: g+x
    - name: chmod 
      file:
        path: /etc/letsencrypt/archive
        mode: g+r
        recurse: yes
    - name: restart nginx
      systemd:
        state: reloaded
        name: nginx
      ignore_errors: yes
