- hosts: all
  tasks:
    - name: vimrc
      copy:
        src: vimrc
        dest: /etc/vimrc
        attributes: +i
    - name: screenrc
      copy:
        src: screenrc
        dest: /etc/screenrc
        attributes: +i
    - name: bashrc
      copy:
        src: bash.bashrc
        dest: /etc/bash.bashrc
        attributes: +i
