- hosts: all
  tasks:
  - name: chattr -i
    file:
      path: /etc/hosts
      attributes: -i
  - name: clear out file
    shell: "echo '' > /etc/hosts"
  - name: localhost
    lineinfile:
      path: /etc/hosts
      line: 127.0.0.1 localhost.localdomain localhost
  - name: localhost
    lineinfile:
      path: /etc/hosts
      line: ::1 localhost.localdomain localhost
  - name: add ipv6
    lineinfile:
      path: /etc/hosts
      line: "{{ lookup('dig', item + '.', 'qtype=AAAA') }} {{ item }} {{ item.split('.')[0] }}"
    loop: "{{ ansible_play_hosts_all }}"
  - name: add ipv4
    lineinfile:
      path: /etc/hosts
      line: "{{ lookup('dig', item + '.') }} {{ item }} {{ item.split('.')[0] }}"
    loop: "{{ ansible_play_hosts_all }}"
  - name: cleanup /etc/hosts
    shell: sed -ni '/^ /!p' /etc/hosts
  - name: chattr +i
    file:
      path: /etc/hosts
      attributes: +i
