- hosts: all
  tasks:
    - name: cat if docker
      shell: "cat /etc/iptables/docker.filter.j2 || true"
      register: cmd_filter
    - name: cat if docker again
      shell: "cat /etc/iptables/docker.nat.j2 || true"
      register: cmd_nat
    - name: set fact if docker
      set_fact:
        more_filter: "{{ cmd_filter.stdout }}"
        more_non_filter: "{{ cmd_nat.stdout }}"
      when: "'docker' in group_names"
    - name: set fact if not docker
      set_fact:
        more_filter: ""
        more_non_filter: ""
      when: "'docker' not in group_names"
    - name: init array
      set_fact:
        ips: []
        ports: []
    - name: resolve ips
      set_fact: ips="{{ ips + [ lookup('dig', item + '.') ] }}"
      loop: "{{ ansible_play_hosts_all }}"
    - name: add http ports
      set_fact: ports="{{ ports + [ '80', '443' ] }}"
      when: "'web' in group_names"
    - name: add mail ports
      set_fact: ports="{{ ports + [ '25', '465', '587', '143', '993' ] }}"
      when: "'mail' in group_names"
    - name: required packages
      pacman:
        name: "{{ item }}"
        state: latest
      loop:
        - iptables
        - sshguard
    - name: chattr -i /etc/iptables/iptables.rules
      file:
        path: /etc/iptables/iptables.rules
        attributes: -i
    - name: create iptables.rules
      template:
        src: iptables.j2
        dest: /etc/iptables/iptables.rules
    - name: chattr +i /etc/iptables/iptables.rules
      file:
        path: /etc/iptables/iptables.rules
        attributes: +i
    - name: enable/restart iptables
      systemd:
        state: restarted
        enabled: yes
        name: iptables
    - name: enable/restart sshguard
      systemd:
        state: restarted
        enabled: yes
        name: sshguard
