- hosts: "{{ hosts_keyword }}"
  tasks:
    - name: init array
      set_fact:
        ips: []
        ports: []
    - name: resolve ips
      set_fact: ips="{{ ips + [ lookup('dig', item + '.') ] }}"
      loop: "{{ machines }}"
    - name: add http ports
      set_fact: ports="{{ ports + [ '80', '443' ] }}"
      when: "'web' in group_names"
    - name: add mail ports
      set_fact: ports="{{ ports + [ '25', '465', '587', '143', '993' ] }}"
      when: "'mail' in group_names"
    - name: create iptables.rules
      template:
        src: iptables.j2
        dest: /etc/iptables/iptables.rules
