- hosts: "{{ hosts_keyword }}"
  tasks:
    - name: init array
      set_fact: ips="[]"
    - name: resolve ips
      set_fact: ips="{{ips}} + [{{ lookup('dig', item + '.')}}]"
      loop: "{{ machines }}"
    - name: create iptables.rules
      template:
        src: iptables.j2
        dest: /root/iptables.rules
