- hosts: all
  tasks:
    - name: init array
      set_fact:
        ips: []
        ports: []
    - name: resolve ips
      set_fact: ips="{{ ips + [ lookup('dig', item + '.') ] }}"
      loop: "{{ ansible_play_hosts_all }}"
    - name: add http ports
      set_fact: ports="{{ ports + [ '80', '443' ] }}"
      when: "'web' in group_names"
    - name: add mail ports
      set_fact: ports="{{ ports + [ '25', '465', '587', '143', '993' ] }}"
      when: "'mail' in group_names"
    - name: required packages
      pacman:
        name:
          - iptables
          - sshguard
        state: latest
    - name: dump iptables rules
      shell: "iptables-save > /etc/iptables/iptables.temp"
    - name: extract nat
      shell: "echo '*nat' > /etc/iptables/nat.rules"
      when: "'ansible' in group_names or 'nat' in group_names"
    - name: extract ansible nat
      shell: "awk '/*nat/{flag=1;next}/COMMIT/{flag=0}flag' /etc/iptables/iptables.temp >> /etc/iptables/nat.rules"
      when: "'ansible' in group_names"
    - name: print extra nat
      copy:
        content: "{{ other_nat_entry }}"
        dest: /etc/iptables/other.nat.rules
      when: "'nat' in group_names"
    - name: extract extra nat
      shell: "cat /etc/iptables/other.nat.rules >> /etc/iptables/nat.rules"
      when: "'nat' in group_names"
    - name: extract nat newline
      shell: "echo -e '\n' >> /etc/iptables/nat.rules"
      when: "'ansible' in group_names or 'nat' in group_names"
    - name: extract nat
      shell: "echo 'COMMIT' >> /etc/iptables/nat.rules"
      when: "'ansible' in group_names or 'nat' in group_names"
    - name: extract docker forwarding if ansible
      shell: "echo '-A FORWARD -j DOCKER-USER' > /etc/iptables/fw.rules"
      when: "'ansible' in group_names"
    - name: extract docker forwarding if ansible
      shell: "awk '/-A FORWARD -j DOCKER-USER/{flag=1;next}/-A DOCKER-USER -j RETURN/{flag=0}flag' /etc/iptables/iptables.temp >> /etc/iptables/fw.rules"
      when: "'ansible' in group_names"
    - name: extract docker forwarding if ansible
      shell: "echo '-A DOCKER-USER -j RETURN' >> /etc/iptables/fw.rules"
      when: "'ansible' in group_names"
    - name: extract sshguard blacklists
      shell: "awk '/-A open -j ACCEPT/{flag=1;next}/COMMIT/{flag=0}flag' /etc/iptables/iptables.temp > /etc/iptables/sshguard.rules"
    - name: cat ssh rules
      shell: "cat /etc/iptables/sshguard.rules || true"
      register: sshguard_filter
    - name: init extras
      set_fact:
        nat: ''
        fw: ''
        sshguard_blacklist: "{{ sshguard_filter.stdout }}"
    - name: cat if nat
      shell: "cat /etc/iptables/nat.rules || true"
      register: cmd_nat
      when: "'ansible' in group_names or 'nat' in group_names"
    - name: cat if fw
      shell: "cat /etc/iptables/fw.rules || true"
      register: cmd_fw
      when: "'ansible' in group_names"
    - name: set fact if nat
      set_fact:
        nat: "{{ cmd_nat.stdout }}"
      when: "'nat' in group_names or 'ansible' in group_names"
    - name: set fact if fw
      set_fact:
        fw: "{{ cmd_fw.stdout }}"
      when: "'fw' in group_names or 'ansible' in group_names"
    - name: chattr -i
      file:
        path: /etc/iptables/iptables.rules
        attributes: -i
        state: touch
    - name: create iptables.rules
      template:
        src: iptables.j2
        dest: /etc/iptables/iptables.rules
        attributes: +i
    - name: cleanup
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/iptables/iptables.temp
        - /etc/iptables/nat.rules
        - /etc/iptables/fw.rules
        - /etc/iptables/sshguard.rules
    - name: enable/restart iptables
      systemd:
        enabled: yes
        state: restarted
        name: iptables
      register: iptables_restarted
      until: iptables_restarted is not failed
      retries: 5
      delay: 2
    - name: enable/restart sshguard
      systemd:
        state: restarted
        enabled: yes
        name: sshguard
    - name: enable/restart docker
      systemd:
        state: restarted
        enabled: yes
        name: docker
      when: "'docker' in group_names and 'ansible' not in group_names"
