- hosts: all
  tasks:
    - name: init array
      set_fact:
        ips: []
        ports: []
    - name: resolve ipv4
      set_fact: ips="{{ ips + [ lookup('dig', item + '.', 'qtype=A') ] }}"
      loop: "{{ ansible_play_hosts_all }}"
    - name: resolve ipv6
      set_fact: ips="{{ ips + [ lookup('dig', item + '.', 'qtype=AAAA') ] }}"
      loop: "{{ ansible_play_hosts_all }}"
    - name: required packages on mailserver
      pacman:
        name:
          - dovecot
          - mailman
        state: latest
      when: "'mail' in group_names"
    - name: required packages on relays
      pacman:
        name:
          - exim
        state: latest
      when: "'mail' not in group_names"
    - name: exim is in ssl group
      user:
        name: exim
        groups: ssl
    - name: dovecot is in ssl group
      user:
        name: dovecot
        groups: ssl
      when: "'mail' in group_names"
    - name: mailman is in ssl group
      user:
        name: mailman
        groups: ssl
      when: "'mail' in group_names"
    - name: chattr -i /etc/mail/exim.conf
      file:
        path: /etc/mail/exim.conf
        attributes: -i
    - name: create exim.conf on mailserver
      template:
        src: exim-main.j2
        dest: /etc/mail/exim.conf
      when: "'mail' in group_names"
    - name: create exim.conf on relays
      template:
        src: exim-relay.j2
        dest: /etc/mail/exim.conf
      when: "'mail' not in group_names"
    - name: check config
      command: exim -C /root/exim.conf -bV
    - name: chattr +i /etc/mail/exim.conf
      file:
        path: /etc/mail/exim.conf
        attributes: +i
    - name: enable/restart iptables
      systemd:
        state: restarted
        enabled: yes
        name: exim
