- hosts: all
  tasks:
    - name: upgrade system packages
      pacman:
        state: latest
        name:
          - pacman
          - glibc
          - linux-lts
          - linux-lts-headers
          - linux
          - linux-headers
          - systemd
          - systemd-sysvcompat
          - libsystemd
    - name: Reboot to get new kernel
      reboot:
        reboot_timeout: 3600
        connect_timeout: 30
      when: "'ansible' not in group_names and 'tor' not in group_names"
      
