- hosts: all
  tasks:
    - name: required packages
      pacman:
        name:
          - screen
          - vim
          - openssh
          - wget
          - git
          - htop
          - net-tools
          - nmap
          - nginx
          - certbot
          - cronie
          - syslog-ng
          - docker
          - prometheus-node-exporter
          - base-devel
          - netctl
          - openvpn
          - iptables
          - sshguard
        state: latest
    - name: all but mail packages
      pacman:
        name:
          - exim
        state: latest
      when: "'mail' not in group_names"
    - name: mail packages
      pacman:
        name:
          - dovecot
          - mailman
        state: latest
      when: "'mail' in group_names"
    - name: ldap packages
      pacman:
        name:
          - slapd
        state: latest
      loop:
      when: "'ldap' in group_names"
