- hosts: "{{ hosts_keyword }}"
  tasks:
    - name: chattr -i /etc/ssh/sshd_config
      file:
        path: /etc/ssh/sshd_config
        attributes: -i
    - name: sshd_config
      template:
        src: sshd_config.j2
        dest: /etc/ssh/sshd_config
    - name: enable/restart sshd
      systemd:
        state: restarted
        enabled: yes
        name: sshd
    - name: chattr +i /etc/ssh/sshd_config
      file:
        path: /etc/ssh/sshd_config
        attributes: +i
