- hosts: all
  tasks:
    - name: required packages
      pacman:
        name: openssh
        state: latest
    - name: chattr -i /etc/ssh/sshd_config
      file:
        path: /etc/ssh/sshd_config
        attributes: -i
    - name: sshd_config
      template:
        src: sshd_config.j2
        dest: /etc/ssh/sshd_config
    - name: enable/restart sshd
      systemd:
        state: restarted
        enabled: yes
        name: sshd
    - name: chattr +i /etc/ssh/sshd_config
      file:
        path: /etc/ssh/sshd_config
        attributes: +i
    - name: chattr -i /etc/ssh/ssh_config
      file:
        path: /etc/ssh/ssh_config
        attributes: -i
    - name: ssh_config
      template:
        src: ssh_config.j2
        dest: /etc/ssh/ssh_config
    - name: chattr +i /etc/ssh/ssh_config
      file:
        path: /etc/ssh/ssh_config
        attributes: +i

