- hosts: all
  tasks:
    - name: add sysadmin
      user:
        name: sysadmin
        comment: sysadmin
        uid: 500
        system: yes
        create_home: yes
        update_password: on_create
    - name: add sysadmin .ssh
      file:
        name: /home/sysadmin/.ssh
        state: directory
        owner: sysadmin
        group: sysadmin
    - name: chattr -i /sysadmin/.ssh/authorized_keys
      file:
        path: /sysadmin/.ssh/authorized_keys
        attributes: -i
        state: touch
        owner: sysadmin
        group: sysadmin
    - name: authorized_keys
      copy:
        content: "{{ authorized_keys }}"
        dest: /sysadmin/.ssh/authorized_keys
        mode: '0600'
    - name: chattr +i /sysadmin/.ssh/authorized_keys
      file:
        path: /sysadmin/.ssh/authorized_keys
        attributes: +i
