- hosts: all
  tasks:
    - name: add sysadmin
      user:
        name: sysadmin
        comment: sysadmin
        uid: 500
        system: yes
        create_home: yes
        update_password: on_create
    - name: add sysadmin .ssh
      file:
        name: /home/sysadmin/.ssh
        state: directory
        owner: sysadmin
        group: sysadmin
    - name: add sysadmin .ssh/authorized_keys
      file:
        name: /home/sysadmin/.ssh/authorized_keys
        state: touch
        owner: sysadmin
        group: sysadmin
