- hosts: all
  tasks:
    - name: install syslog-ng
      pacman:
        name:
          - syslog-ng
        state: latest
    - name: syslog-ng.conf
      copy:
        src: syslog-ng.conf
        dest: /etc/syslog-ng/syslog-ng.conf
        attributes: +i
    - name: syslog-ng-recv.conf
      file:
        path: /etc/syslog-ng/syslog-ng-recv.conf
        state: absent
      when: "'monitoring' in group_names"
    - name: syslog-ng-recv.conf
      template:
        src: syslog-ng-recv.conf.j2
        dest: /etc/syslog-ng/syslog-ng-recv.conf
        attributes: +i
      when: "'monitoring' in group_names"
    - name: syslog-ng-recv.conf
      file:
        path: /etc/syslog-ng/syslog-ng-recv.conf
        attributes: +i
        state: touch
      when: "'monitoring' not in group_names"
    - name: syslog-ng-send.conf
      file:
        path: /etc/syslog-ng/syslog-ng-send.conf
        state: absent
      when: "'monitoring' in group_names"
    - name: syslog-ng-send.conf
      template:
        src: syslog-ng-send.conf.j2
        dest: /etc/syslog-ng/syslog-ng-send.conf
        attributes: +i
      when: "'monitoring' not in group_names"
    - name: syslog-ng-send.conf
      file:
        path: /etc/syslog-ng/syslog-ng-send.conf
        attributes: +i
        state: touch
      when: "'monitoring' in group_names"
    - name: enable/restart syslog-ng
      systemd:
        state: restarted
        enabled: yes
        name: syslog-ng@default
