- hosts: all
  tasks:
    - name: add group 'users'
      group:
        gid: 100
        name: users
        state: present
        system: yes
    - name: add group 'wheel'
      group:
        gid: 600
        name: wheel
        state: present
        system: yes
    - name: add users
      user:
        name: "{{ item.username }}"
        comment: "{{ item.username }}"
        uid: "{{ item.uid }}"
        system: no
        create_home: yes
        password: "{{ item.crypt }}"
        update_password: on_create
        group: users
      loop: "{{ user_list }}"
    - name: add user .ssh
      file:
        name: "/home/{{ item.username }}/.ssh"
        state: directory
        owner: "{{ item.username }}"
        group: users
      loop: "{{ user_list }}"
    - name: authorized_keys
      copy:
        content: "{{ item.authorized_keys }}"
        dest: "/home/{{ item.username }}/.ssh/authorized_keys"
        owner: "{{ item.username }}"
        group: users
        mode: '0600'
        force: no
      loop: "{{ user_list }}"
