- hosts: "{{ hosts_keyword }}"
  tasks:
  - name: Write a file
    copy:
      content: "{{ content }}"
      dest: "{{ dest }}"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'
