- hosts: all
  tasks:
  - name: chattr -i
    file:
      path: "{{ dest }}"
      attributes: -i
      state: touch
  - name: Write a file
    copy:
      content: "{{ content }}"
      dest: "{{ dest }}"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'
  - name: chattr +i
    file:
      path: "{{ dest }}"
      attributes: +i
